import Vue from 'vue'
import { Button, Icon, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Lazyload, ActionSheet, Dialog, Rate, Checkbox, Tab, Tabs } from 'vant'

Vue.use(Button)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Search)
Vue.use(Toast)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Lazyload)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Rate)
Vue.use(Checkbox)
Vue.use(Tab)
Vue.use(Tabs)
